# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go build

env:
  CGO_ENABLED: 0

on:
  workflow_dispatch:
  push:
    branches: [ "ci_build_demo" ]
    paths:
      - '.github/workflows/go_build.yml'

jobs:

  build:
    runs-on: ${{ matrix.os }}

    # create a build matrix for jobs
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - postfix: .exe
            os: windows-latest
          - postfix: ""
            os: macos-latest
          - postfix: ""
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Build
      run: go build -ldflags="-w -s" -o output/main${{ matrix.postfix }} -v ./bin/cmd/main.go

    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Release-${{ matrix.os }}
        path: output/*
