# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go test

on:
  push:
    branches: ['crlf']
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'doc/**'
      - 'example/**'
      - 'template/**'
      - 'README.md'
      - 'Dockerfile'
      - '.*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4

    - name: Build
      run: CGO_ENABLED=0 go build -ldflags="-w -s" -v ./bin/cmd/main.go

    - name: Build apiserver
      run: CGO_ENABLED=0 go build -ldflags="-w -s" -o apiserver -v ./bin/apiserver/main.go

    - name: Test
      # -race needs CGO_ENABLED=1
      run: go test -race -v ./...

    - name: Setup Kubernetes cluster (KIND)
      uses: helm/kind-action@v1
      with:
        version: v0.23.0
        node_image: kindest/node:v1.30.0

    - name: Test with KIND
      run: |
        kubectl cluster-info
        kubectl describe node
        ./main -c ./test/kind/config.conf
        awk -F ',' 'NR!=1{print $4}' ./test.csv | diff test/kind/TestResult.txt -
